# Generated by Django 6.0.7 on 2026-07-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='company_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='target_audience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaignbrief',
            name='required_niche',
            field=models.CharField(default='tech', max_length=50),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='engagement_rate',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=4),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='niche',
            field=models.CharField(choices=[('tech', 'Technology & AI'), ('gaming', 'Gaming & Esports'), ('lifestyle', 'Lifestyle & Vlogs'), ('fashion', 'Fashion & Beauty'), ('fitness', 'Fitness & Health'), ('finance', 'Finance & Investing')], default='tech', max_length=50),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='primary_platform',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('twitch', 'Twitch')], default='youtube', max_length=20),
        ),
    ]
