# Generated by Django 6.0.7 on 2026-07-24 07:04

from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
        ('core_engine', '0002_brandprofile_company_size_brandprofile_logo_url_and_more'),
    ]

    operations = [
        VectorExtension(),
    ]
