# Generated by Django 6.0.7 on 2026-07-24 09:03

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine', '0003_enable_pgvector'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddIndex(
            model_name='creatorprofile',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='creator_vector_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
