# Generated by Django 6.0.7 on 2026-07-27 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine', '0005_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignbrief',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns_brief', to='core_engine.brandprofile'),
        ),
    ]
