# Generated by Django 6.0.7 on 2026-07-29 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine', '0006_alter_campaignbrief_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='budget',
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='points_balance',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='campaign',
            name='points_reward',
            field=models.PositiveIntegerField(default=0, help_text='Points awarded to creator upon completion'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='points_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CampaignApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch', models.TextField(blank=True, help_text='Why the creator is a good fit')),
                ('submission_link', models.URLField(blank=True, help_text='Link to deliverable/content', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted / Hired'), ('rejected', 'Rejected'), ('submitted', 'Work Submitted'), ('completed', 'Completed & Paid')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core_engine.campaign')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core_engine.creatorprofile')),
            ],
            options={
                'unique_together': {('campaign', 'creator')},
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('transaction_type', models.CharField(choices=[('campaign_payout', 'Campaign Payout'), ('admin_grant', 'Admin Grant'), ('top_up', 'Brand Top-Up')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_engine.brandprofile')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_engine.campaign')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_engine.creatorprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='CampaignBrief',
        ),
    ]
