# Generated by Django 6.0.7 on 2026-07-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine', '0007_remove_campaign_budget_brandprofile_points_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='creators_needed',
            field=models.IntegerField(default=1),
        ),
    ]
