# Generated by Django 6.0.7 on 2026-07-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine', '0008_campaign_creators_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_niche',
            field=models.CharField(default='tech', max_length=100),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_platform',
            field=models.CharField(default='youtube', max_length=100),
        ),
        migrations.AlterField(
            model_name='campaignapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('offered', 'Offered by Brand'), ('accepted', 'Accepted / Hired'), ('rejected', 'Rejected'), ('submitted', 'Work Submitted'), ('completed', 'Completed & Paid')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='niche',
            field=models.CharField(default='tech', max_length=255),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='primary_platform',
            field=models.CharField(default='youtube', max_length=255),
        ),
    ]
