# Generated by Django 6.0.7 on 2026-07-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine', '0009_campaign_end_date_campaign_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='duration_hours',
            field=models.PositiveIntegerField(blank=True, default=24, help_text='Campaign duration in hours', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='start_datetime',
            field=models.DateTimeField(blank=True, help_text='Exact launch date and time', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
