# Generated by Django 6.0.7 on 2026-08-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine', '0010_campaign_duration_hours_campaign_start_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignapplication',
            name='submission_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline date & time to submit work', null=True),
        ),
        migrations.AddField(
            model_name='campaignapplication',
            name='work_description',
            field=models.TextField(blank=True, help_text='Deliverable instructions set by Brand', null=True),
        ),
    ]
