# Generated by Django 6.0.7 on 2026-08-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine', '0011_campaignapplication_submission_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignapplication',
            name='feedback',
            field=models.TextField(blank=True, help_text='Feedback/review written by Brand upon completion', null=True),
        ),
        migrations.AddField(
            model_name='campaignapplication',
            name='rating',
            field=models.PositiveIntegerField(blank=True, help_text='Rating given by Brand upon completion (1 to 5 stars)', null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='rating',
            field=models.FloatField(default=5.0, help_text='Average brand rating (1.0 to 5.0)'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='total_ratings_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of brand ratings received'),
        ),
    ]
