# Generated by Django 6.0.7 on 2026-08-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine', '0012_campaignapplication_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='start_date',
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Company overview & mission statement', null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text='Brand social channels', null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='deliverables_format',
            field=models.CharField(blank=True, default='Sponsored Video / Post', help_text='Content format required', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text="Social media profiles dict e.g. {'twitter': '...', 'instagram': '...'}", null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
