# Generated by Django 6.0.7 on 2026-08-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine', '0013_remove_campaign_end_date_remove_campaign_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignapplication',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when work deliverable was submitted by creator', null=True),
        ),
        migrations.AlterField(
            model_name='campaignapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('offered', 'Offered by Brand'), ('accepted', 'Accepted / Hired'), ('rejected', 'Rejected'), ('expired', 'Expired (Deadline Missed)'), ('submitted', 'Work Submitted'), ('completed', 'Completed & Paid')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='rating',
            field=models.FloatField(default=0.0, help_text='Average brand rating (0.0 to 5.0)'),
        ),
    ]
