# Generated by Django 6.0.7 on 2026-08-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine', '0014_campaignapplication_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason provided by Brand when rejecting submitted work', null=True),
        ),
    ]
